### ISSUE TITLE
function call segmentation

### ISSUE THREAD

**Issue by youpong** [youpong/9cc#6]
execute the code. segmentation fault occurs.

int test_issues5() {
  int a;
  expect(1, 0, 1);
  return 21;
}

int main() {
  test_issues5();
  return 22;
}

**Comment by machipon** [comment]
これこれ

iPhoneから送信

2019/06/03 21:18、youpong <notifications@github.com>のメール:

**Comment by youpong** [comment]
fix with af60cb3fd10d2ee85fb71e12ff3aee72f95a85bc
